ALTER TABLE channel ADD COLUMN IF NOT EXISTS visibility TEXT NOT NULL DEFAULT 'public';
ALTER TABLE channel ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE message ADD COLUMN IF NOT EXISTS parent_id UUID REFERENCES message(id);
ALTER TABLE message ADD COLUMN IF NOT EXISTS type TEXT NOT NULL DEFAULT 'text';
ALTER TABLE message ADD COLUMN IF NOT EXISTS is_impersonated BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE message ADD COLUMN IF NOT EXISTS reply_expected BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_message_parent ON message(parent_id);
CREATE INDEX IF NOT EXISTS idx_message_type ON message(type);
